import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "@/styles/global.css";
import Navbar from "@/components/layout/navbar/Navbar";
import themeColors from "@/theme/colors";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Arsalan Ahmed Portfolio",
  description: "Generated by create next app",
};

const bgColor = themeColors.main.primary;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable}`}
        style={{ "--background-color": bgColor } as React.CSSProperties}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
